stages:
  - build
  - test
  - release

variables:
  CONTAINER_TEST_IMAGE: hugomrdias/ansible:$CI_BUILD_REF_NAME
  CONTAINER_RELEASE_IMAGE: hugomrdias/ansible:latest

build:
  image: docker:latest
  services:
    - docker:dind
  stage: build
  script:
    - docker login -u hugomrdias -p $DOCKER_HUB_PASS
    - docker build --pull -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE

test:
  stage: test
  image: $CONTAINER_TEST_IMAGE
  script:
    - ansible localhost -m setup
    - ansible-galaxy install hugomrdias.basic


release:
  stage: release
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u hugomrdias -p $DOCKER_HUB_PASS
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE
  only:
    - master
