stages:
  - build
  - test
  - release

build:
  image: docker:latest
  services:
    - docker:dind
  stage: build
  script:
    - docker login -u hugomrdias -p $DOCKER_HUB_PASS
    - docker build -f debian/Dockerfile --pull -t hugomrdias/ansible:debian-test .
    - docker push hugomrdias/ansible:debian-test
    - docker build -f ubuntu/Dockerfile --pull -t hugomrdias/ansible:ubuntu-test .
    - docker push hugomrdias/ansible:ubuntu-test

test-debian:
  stage: test
  image: hugomrdias/ansible:debian-test
  script:
    - ansible --version
    - ansible localhost -m setup
    - ansible-galaxy install hugomrdias.basic

test-ubuntu:
  stage: test
  image: hugomrdias/ansible:ubuntu-test
  script:
    - ansible --version
    - ansible localhost -m setup
    - ansible-galaxy install hugomrdias.basic

release:
  stage: release
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u hugomrdias -p $DOCKER_HUB_PASS
    - docker pull hugomrdias/ansible:debian-test
    - docker tag hugomrdias/ansible:debian-test hugomrdias/ansible:debian
    - docker push hugomrdias/ansible:debian
    - docker pull hugomrdias/ansible:ubuntu-test
    - docker tag hugomrdias/ansible:ubuntu-test hugomrdias/ansible:ubuntu
    - docker push hugomrdias/ansible:ubuntu
  only:
    - master
